### ISSUE TITLE
Feature Request: Methods to read and/or retrieve notes from the network

### ISSUE THREAD

**Issue by dtrammell** [dtonon/nostr-ruby#2]
All the methods available thus far are for configuring the Nostr class instance and posting note events of various types to the network.  We need some methods to retrieve notes or read notes received from the network as well.  Great work so far!

**Comment by dtonon** [comment]
The method is already present, but "hidden" in the code:
https://github.com/dtonon/nostr-ruby/blob/master/lib/nostr_ruby.rb#L243

Check the [nostr ruby playground](https://github.com/dtonon/nostr-ruby-playground) (the project from which I extracted the gem) for some examples:

7 - [Private chat](https://github.com/dtonon/nostr-ruby-playground/blob/main/07-private-chat.rb)
8 - [Notifier by keywords](https://github.com/dtonon/nostr-ruby-playground/blob/main/08-notifier.rb)

I have to define the API structure, now is quite casual, and then I will implement read methods better.

**Comment by dtrammell** [comment]
Ah, it's there just not documented...  Thanks!  Will check it out (:

**Comment by iraszl** [comment]
Thanks for the gem and the instructions above. I'm unable to figure this out. Can you kinly provide a sample code to retrieve messages from a user using a npub?

**Comment by dtonon** [comment]
@iraszl if you check my previous message you can find two complete examples; they don't use this library but for REQ events you have to build the filter by hand, so the difference is little.

This is a working example:

```ruby
require 'json'
require 'nostr_ruby'
require 'faye/websocket'
require 'eventmachine'

EM.run {

  n = Nostr.new(public_key: 'not_relevant')
  req_event = n.build_req_event({ "kinds": [1], "#p": ["50d94fc2d8580c682b071a542f8b1e31a200b0508bab95a33bef0855df281d63"], "since": (Time.now.utc - 86400).to_i  })

  ws = Faye::WebSocket::Client.new("wss://nostr.wine", [], {ping: 60, :tls => {:verify_peer => false}})

  ws.on :open do |event|
    puts req_event.inspect
    ws.send req_event.to_json
  end

  ws.on :message do |msg|
    event = JSON.parse(msg.data)
    puts event[2]["content"] if event[0] == "EVENT"
  end

}
```

Now nostr_ruby require a key (private or public) to initialize the object, for REQs is not mandatory, so in this example I simply pass a fake string. In the future I will polish this part.
